site_name: quantKit
repo_url: https://github.com/larrykann/quantKit

theme:
  name: material
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: sakura
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: aizome
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - API Reference:
    - Data: 
      - Overview: reference/quantKit.data.md
      - DataContainer: reference/quantKit.data.container.md
      - Schemas: reference/quantKit.data.schemas.md
      - Validation: reference/quantKit.data.validation.md
      - Adapters: reference/quantKit.data.adapters.md
    - Financial:
      - Interest: reference/quantKit.financial.interest.md
      - Returns: reference/quantKit.financial.returns.md
    - Stochastics:
      - Utils: reference/quantKit.stochastic.utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
