site_name: quantKit
repo_url: https://github.com/larrykann/quantKit

nav:
  - Home: index.md
  - API Reference:
    - Data:
      - DataContainer: reference/quantKit.data.container.md
      - Schemas: reference/quantKit.data.schemas.md
      - Validation: reference/quantKit.data.validation.md
      - Adapters: reference/quantKit.data.adapters.md
    - Stochastics:
      - Utils: reference/quantKit.stochastic.utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src

theme:
  name: material
