site_name: quantKit
repo_url: https://github.com/larrykann/quantKit

theme:
  name: material
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: sakura
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: aizome
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - User Guide:
    - Importing Data: user-guide/importing-data.md
    - Binary Files: user-guide/working-with-binary-files.md
    - Strategies: user-guide/strategies.md
  - Technical Guides:
    - Binary Format Specification: technical-guides/binary-format-spec.md
    - Datetime Deepdive: technical-guides/datetime-deepdive.md
    - Performance Tips: technical-guides/performance-tips.md
  - Mathematical Foundations:
    - Finance:
      - Simple Interest: foundations/finance/simple-interest.md
      - Returns: foundations/finance/simple-returns.md
  - API Reference:
    - Data:
      - Schemas: reference/data/quantKit.data.schemas.md
    - Financial:
      - Interest: reference/financial/quantKit.financial.interest.md
      - Returns: reference/financial/quantKit.financial.returns.md
    - Stochastic:
      - Utils: reference/stochastic/quantKit.stochastic.utils.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
